import type { Metadata } from "next"; 

export const metadata: Metadata = {
  title: "Excaildraw",
  description: "Generated by ab",
};


type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body> 
            {children} 
        </body>
      </html>
    </>
  )
}